name: 🚀 DevSecOps Pipeline

on:
  push:
    branches:
      - main  # 🎯 Target branch for automation

jobs: 
  sonarcloud:
    name: 🔍 SonarCloud Analysis
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures full history for better analysis
      - name: 🛠️ SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 🔑 Required for PR details
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 

  snyk_scan:
    name: 🛡️ Snyk Security Scan (PHP)
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v3

      - name: 🔎 Run Snyk Security Scan
        uses: snyk/actions/php@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          run: snyk test ./web

  zap_scan:
    name: ⚡ ZAP Full Scan (Final Step)
    runs-on: ubuntu-latest
    needs: [sonarcloud, snyk_scan]  # Ensures ZAP runs last after SonarCloud & Snyk
    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4
        with:
          ref: main
      - name: 🕷️ Run ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          token: ${{ secrets.GIT_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable' 
          target: 'http://wordpress-lb-1672391006.us-east-1.elb.amazonaws.com/'  # Replace with actual application URL
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'  # Additional ZAP options if required
